#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Read package.json
const packageJsonPath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

const { name, version } = packageJson;
const clientVersion = `typescript/${name}@${version}`;

// Generate version.ts
const versionFilePath = path.join(__dirname, '..', 'src', 'version.ts');
const content = `// This file is auto-generated by scripts/update-version.js
// Do not edit manually
export const CLIENT_VERSION = '${clientVersion}';
`;

fs.writeFileSync(versionFilePath, content, 'utf8');
console.log(`✅ Generated version.ts with CLIENT_VERSION: ${clientVersion}`);
